NumPy is a powerful library for numerical computing in Python, and it includes a variety of functions for linear algebra operations. Here are some of the key linear algebra functions available in NumPy:

# Vector and Matrix Creation:


*   `numpy.array`: Creates an array from a list or tuple.
*   `numpy.zeros` and `numpy.ones` : Generates arrays filled with zeros or ones.


*   `numpy.eye`: Creates an identity matrix.





In [1]:
import numpy as np

# Example of array creation
arr = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Example of zeros, ones, and identity matrix creation
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 4))
identity_matrix = np.eye(3)

In [2]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Matrix Operations:



*   `numpy.dot` or `@`: Performs matrix multiplication.
*   `numpy.transpose` or `.T`: Transposes a matrix.



In [9]:
# Example of matrix multiplication and transpose
result = np.dot(matrix, arr)
transposed_matrix = matrix.T

In [11]:
result

array([14, 32])

In [12]:
transposed_matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

# Matrix Inversion and Determinant:


*   `numpy.linalg.inv`: Computes the inverse of a square matrix.
*   `numpy.linalg.det`: Calculates the determinant of a square matrix.

In [15]:
# Example of matrix inversion and determinant
matrix = np.array([[1,2],[3,4]])
inverse_matrix = np.linalg.inv(matrix)
determinant_value = np.linalg.det(matrix)


In [16]:
inverse_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
determinant_value

-2.0000000000000004

# Eigenvalues and Eigenvectors:


*   `numpy.linalg.eig`: Computes the eigenvalues and eigenvectors of a square matrix.



In [18]:
# Example of eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [19]:
eigenvalues

array([-0.37228132,  5.37228132])

In [20]:
eigenvectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

#Solving Linear Systems:


*   `numpy.linalg.solve`: Solves a linear system of equations.

  

> The system of linear equations corresponding to the given NumPy code is:\
2x + 3y = 5\
4x + 5y = 7




In [21]:
# Example of solving a linear system
coefficients = np.array([[2, 3], [4, 5]])
constants = np.array([5, 7])
solution = np.linalg.solve(coefficients, constants)


~ diptiranjan